version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - '8080:8080'
    tty: true
    init: true
    privileged: true
    platform: linux/x86_64
    volumes:
      - ./:/var/www:cached
    networks:
      net1:
        ipv4_address: 192.168.10.10
networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
